name: Update Ontario polling graphics
on:
  schedule:
    - cron: 0 16 * * *

jobs:
  update_charts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update line charts (English and French)
        env: 
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: python3 script-ontario.py

      - name: Update tables (English and French)
        env: 
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: |
          export LC_ALL="en_US.UTF-8"
          export LC_CTYPE="en_US.UTF-8"
          sudo dpkg-reconfigure locales
          python3 script-tables.py
